env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: { "no-param-reassign": [2, { "props": false }], "no-underscore-dangle": 0, "func-names": ["warn", "as-needed"] }
